### ISSUE TITLE
Parsing stalls on complex `font-family`

### ISSUE THREAD

**Issue by amiller-gh** [mahirshah/css-property-parser#33]
The parser hangs when parsing `font-family`. Specific decl it is having trouble with in my case is:

```css
:scope {
  font-family: -apple-system, system-ui, "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Fira Sans", "Ubuntu", "Oxygen", "Oxygen Sans", "Cantarell", "Droid Sans", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Lucida Grande", "Helvetica", "Arial", sans-serif;
}
```
